name: Publish Userscript

on: 
  [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: python3 build.py
